codento/portfolio-visualiser

- Development/visualizer/portfolio_manager/templates/data.csv
- Development/visualizer/portfolio_manager/urls.py
> Should work testdata

- Development/visualizer/portfolio_manager/importer.py
- Development/visualizer/portfolio_manager/serializers.py
- Development/visualizer/portfolio_manager/templates/navbar.html
- Development/visualizer/portfolio_manager/templates/path.html
- Development/visualizer/portfolio_manager/templates/visualizations.html
- Development/visualizer/portfolio_manager/test_importer.py
- Development/visualizer/portfolio_manager/test_models.py
- Development/visualizer/portfolio_manager/test_views.py
- Development/visualizer/portfolio_manager/urls.py
- Development/visualizer/portfolio_manager/views.py
Made a visualizationpage wiht buttons for different visualizations. Currently only path is linked to anything
> Visualizationspage

- Development/visualizer/.gitignore
- Development/visualizer/portfolio_manager/importer.py
- Development/visualizer/portfolio_manager/test_importer.py
OwningOrganization is now imported inoto project.parent. project's name dimension can now be any column in google sheet.
> fix organization import from google sheet

- Development/visualizer/portfolio_manager/static/portfolio_manager/css/project.css
- Development/visualizer/portfolio_manager/templates/project.html
Sidebar now works as intended. Mostly css hax
> Fix sidenav so it looks nice

- Development/visualizer/portfolio_manager/static/portfolio_manager/css/project.css
- Development/visualizer/portfolio_manager/templates/project.html
Made a modify button in the project page on each field. Automatically populates the info based on which field and changes input type. Doesn't however post to anywhere yet, only GET to "" at the moment
> Modify button

- Development/visualizer/portfolio_manager/models.py
- Development/visualizer/portfolio_manager/serializers.py
- Development/visualizer/portfolio_manager/templates/path.html
> Path improvements

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/projectDependencies.js
Skaalaus luotettavampi ja tehokkaampi
> Improved scaling on projectDependancies

- Development/visualizer/portfolio_manager/models.py
- Development/visualizer/portfolio_manager/test_views.py
Just cosmetic changes. Import and json export works on python3. Forget support for python2.
> expect python3

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/projectDependencies.js
Legend showing project color, name and budget
> Dependancy legend

- Development/visualizer/portfolio_manager/views.py
> Comments django

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/projectDependencies.js
Added support to multiple dependancies. Also changed the node identification to be based on strings instead of projectID.
> Projects can now have multiple dependancies

- Development/visualizer/.gitignore
- Development/visualizer/portfolio_manager/templates/path.html
Tästä voi ottaa mallia 4kenttää varten, miten saa parametrien valinta nappulat sidebariin.
> path.html: parameters in sidebar

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/projectDependencies.js
Fixed a bug in the dependancy visualisation
> fixed project-naming bug

- Development/visualizer/portfolio_manager/fixtures/persons_browser_testing.json
- Development/visualizer/portfolio_manager/fixtures/projects.json
- Development/visualizer/portfolio_manager/fixtures/projects_browser_testing.json
- Development/visualizer/portfolio_manager/test_browser.py
- Development/visualizer/portfolio_manager/views.py
Some test cases exercising "modify project" functionality.
> Modify project testcase

- Development/visualizer/.gitignore
- Development/visualizer/portfolio_manager/templates/path.html
- Development/visualizer/portfolio_manager/test_browser.py
- Development/visualizer/portfolio_manager/views.py
Organization are now created with basic project template. Template includes dimensions: SizeMoney, EndDate and ProjectManager.
> Add template to new organization

- Development/visualizer/portfolio_manager/importer.py
> Fix indent problem in importer.py

- Development/visualizer/portfolio_manager/forms.py
- Development/visualizer/portfolio_manager/views.py
cherry-pick 8c9ff3c plus don't clobber post
> Fix add project form

- Development/visualizer/portfolio_manager/views.py
"Click to see all" fails on old var name
> Fix fail to load associated projects in project view

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/projectDependencies.js
Dependencies-visualization scales by the current window size. Defaults to 700*500 for preventing unusable small box.
> Dependency sizing

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/path.js
screen size based scaling of path has now minimum values and stable left margin to ensure the room for the y axis values.
> Minimum size for path container

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/colorGenerator.js
- Development/visualizer/portfolio_manager/static/portfolio_manager/js/fourField.js
- Development/visualizer/portfolio_manager/templates/fourfield.html
Fourfield uses colorGenerator to create enough colours for different organizations and pairs them. This replaces the previous colorization generated directly from company names.
> Fourfield colors

- Development/visualizer/portfolio_manager/test_browser.py
Small test fix. btn-success selector is now btn-orange
> Fix test. btn-success -> btn-orange

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/fourField.js
If possible, this should be tested with IE as well
> Slider handle now visible in firefox as well

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/fourField.js
- Development/visualizer/portfolio_manager/static/portfolio_manager/js/fourfield_loader.js
- Development/visualizer/portfolio_manager/static/portfolio_manager/js/path.js
- Development/visualizer/portfolio_manager/static/portfolio_manager/js/path_loader.js
Moving code that is not needed in path.js to path_loader.js, commenting the code, refactoring some strange implementations.
> Path refactor

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/path_loader.js
Dimensions matching previously selected name are preferred, fall back to first
option for y, first option distinct from y for x.
> Select default axes when project select in path visualization

- Development/visualizer/portfolio_manager/static/portfolio_manager/js/fourField.js
Fourfield visualization shows only projects that are active on selected date.
Projects that have not yet started or are already done will disappear.
> Fourfield excludes projects that are not currently active

- LICENSE
Adding the needed licensing information to files must be done as well.
> changing the license text to GPL

- LICENSE
The previous was just shorter version for the files, my bad
> Right text to license file

- portfolio_manager/fixtures/project_templates.json
- portfolio_manager/fixtures/projects_browser_testing.json
- portfolio_manager/forms.py
- portfolio_manager/importer.py
- portfolio_manager/models.py
- portfolio_manager/serializers.py
- portfolio_manager/static/portfolio_manager/js/fourField.js
- portfolio_manager/static/portfolio_manager/js/fourfield_loader.js
- portfolio_manager/static/portfolio_manager/js/path_loader.js
- portfolio_manager/static/portfolio_manager/js/test_path.js
- portfolio_manager/templates/modals/modify_modal.html
- portfolio_manager/templates/snapshots/single/fourfield.html
- portfolio_manager/templatetags/project_tags.py
- portfolio_manager/test_browser.py
- portfolio_manager/test_forms.py
- portfolio_manager/test_importer.py
- portfolio_manager/test_models.py
- portfolio_manager/test_serializers.py
- portfolio_manager/views.py
Changed DecimalDimension to NumberDimension to better reflect that we dont have any other numbertypes and to work better with inputtypes etc. Also sidequested to fix fourfieldsnapshots quickly
> Decimal to number

- requirements.txt
use `pip install -U -r requirements.txt`  to update those that satisfy the condition but could be better.
> Allow libraries to use highest available feature-compatible version

- portfolio_manager/fixtures/projects_browser_testing.json
- portfolio_manager/fixtures/snapshot.json
- portfolio_manager/templates/modals/save_fourfield_snap_modal.html
- portfolio_manager/templates/modals/save_path_snap_modal.html
- portfolio_manager/test_browser.py
- portfolio_manager/test_models.py
- portfolio_manager/views.py
> Snapshot tests

- portfolio_manager/static/portfolio_manager/css/admin_tools.css
- portfolio_manager/templates/path.html
https://trello.com/c/XJedlGxL
https://trello.com/c/6VsIPKWk
> Button text doesnt overflow. Pathsnap button is grey

- portfolio_manager/static/portfolio_manager/css/sidebar.css
- portfolio_manager/templates/add_project.html
- portfolio_manager/templates/base_visualization.html
- portfolio_manager/templates/homepage.html
- portfolio_manager/templates/projects.html
Went through all files to find all finnish code and translate it.
> Finnish code changed to english

- portfolio_manager/static/portfolio_manager/js/projectDependencies.js
Fix to https://trello.com/c/AwPeRvpO/40-force-pushing-the-dependency-arrows-outside-the-box
> Dependency arrows stay in box and always connect to their circles.

- portfolio_manager/static/portfolio_manager/js/fourfield_loader.js
https://trello.com/c/cuZguTz0
Changed the loader output from field value to datepickers getDate function.
> Fourfield date

- portfolio_manager/static/portfolio_manager/js/path.js
> Path label fix

- portfolio_manager/static/portfolio_manager/css/fourField.css
- portfolio_manager/static/portfolio_manager/css/path.css
- portfolio_manager/static/portfolio_manager/css/projectDependencies.css
- portfolio_manager/static/portfolio_manager/js/projectDependencies.js
https://trello.com/c/z8Ep7CJW
Cleaned up obsolete code from css-files 
Some minor improvements on dependencies texts
> Visualization css cleanup

- portfolio_manager/static/portfolio_manager/js/modify_project.js
- portfolio_manager/views.py
Fixed a bug that made it so that you couldn't add values to fields that didn't have values previously
https://trello.com/c/IOMEZHEd
> You can now add values for fields without previous values

- portfolio_manager/static/portfolio_manager/js/projectDependencies.js
The legend is now ordered by budget on the dependency page
https://trello.com/c/iy4ZC0aM
> Dependency legend is now sorted according to budget

- portfolio_manager/importer.py
Sheet format changed so that 3rd column is for milestone due dates. In a milestone row everything is the same form as in a valuerow except that the due date is filled in
> Importer now works with the new sheet format

- portfolio_manager/static/portfolio_manager/js/path.js
- portfolio_manager/static/portfolio_manager/js/path_loader.js
- portfolio_manager/templates/path.html
https://trello.com/c/0Ry2nYql
Added ability to scale between selected dates.
Date selection is restricted between projects first and last date. Y-axis scales to current view.
> Path datepicker

- portfolio_manager/models.py
- portfolio_manager/static/portfolio_manager/js/projectDependencies.js
- portfolio_manager/static/portfolio_manager/js/snapshot/snap_path_loader.js
- portfolio_manager/templates/fourfield.html
- portfolio_manager/templates/modals/save_path_snap_modal.html
- portfolio_manager/templates/path.html
- portfolio_manager/templates/projectdependencies.html
- portfolio_manager/views.py
https://trello.com/c/uVFlbawX
Removed the bootstrap offset and addressed the div to take all available room on the visualization page.
Added visualization div to dependencies.
> Visualization margin

- README.md
- portfolio_manager/models.py
- portfolio_manager/templates/homepage.html
- portfolio_manager/views.py
Created different behaviour for different user types (superuser, organization admin, employees and outsiders) per site
> Different views

- portfolio_manager/exporter.py
- portfolio_manager/models.py
- portfolio_manager/outlookservice.py
- portfolio_manager/static/portfolio_manager/js/microsoft.js
- portfolio_manager/templates/excel.html
- portfolio_manager/templates/export_excel.html
- portfolio_manager/urls.py
- portfolio_manager/views.py
A working export where you can export to an Microsoft 365 excel sheet. From the same little dropmenu as the import you can now export to that sheet aswell. Currently is hardcoded to export to a sheet named "NewSheet" so if that doesn't exist it fails and if it is already in use it will overwrite the cells it uses. Currently doesn't export milestones and neither AssociatedProjects or AssociatedPersons since these don't have histories because django-simple-history does not support manytomany-fields
> Excel export

- portfolio_manager/importer.py
- portfolio_manager/models.py
- portfolio_manager/templates/project.html
Fixed the some timezone problems. Now the project page doesn't show time, only dates. Also the the datedimension uses the same timezone procedure as the importer to create more consistent behaviour
> Timezone and date formatting

- README.md
- portfolio_manager/exporter.py
- portfolio_manager/importer.py
- portfolio_manager/models.py
- portfolio_manager/outlookservice.py
- portfolio_manager/static/portfolio_manager/js/microsoft.js
- portfolio_manager/static/portfolio_manager/js/path.js
- portfolio_manager/static/portfolio_manager/js/path_loader.js
- portfolio_manager/static/portfolio_manager/js/snapshot/path.js
- portfolio_manager/static/portfolio_manager/js/snapshot/snap_path_loader.js
- portfolio_manager/templates/excel.html
- portfolio_manager/templates/export_excel.html
- portfolio_manager/templates/homepage.html
- portfolio_manager/templates/project.html
- portfolio_manager/templates/snapshots/multiple/all.html
- portfolio_manager/templates/snapshots/multiple/path.html
- portfolio_manager/templates/snapshots/single/path.html
- portfolio_manager/urls.py
- portfolio_manager/views.py
Connecting the path 2.0 to snapshot. 
Adding json as parameter (as it is in 4field). 
Fixing png -> jpg in snapshots page.
Different model for the saved snapshot data.
https://trello.com/c/WZ2anysD
> Path 2.0 snapshot

- portfolio_manager/static/portfolio_manager/js/snapshot/snap_path_loader.js
path snapshot now works with 1 or 0 x-dimensions
> Path snapshot fix

- portfolio_manager/static/portfolio_manager/js/projectDependencies.js
- portfolio_manager/templates/projectdependencies.html
-D3v3 was changed to d3v4, Legend colors are now matched with the dependancies circles, and the colors scale was changed to colorGenerator.js. 
https://trello.com/c/Sf9NDtuf (d3v4 change)
https://trello.com/c/TLwk9MP2 (color scale change)
https://trello.com/c/MVxLTe0q (dependancies color don't match with legend)
> Dependencies fixes

- portfolio_manager/static/portfolio_manager/js/fourField.js
https://trello.com/c/v1ufZtNH
(and)
https://trello.com/c/wwo43iGQ
fourfield circle radiuses now scale with d3 linearscale. For some reason the linearscale returns values outside its range when the value is large, so a maximum radius variable has been added and set to 100px (maximumRadius).
> Fourfield scaling

- portfolio_manager/templates/about.html
https://trello.com/c/niOxqTlk
Updated the about-page to be less school oriented, added licensing information.
> About-page update

- portfolio_manager/static/portfolio_manager/js/fourField.js
https://trello.com/c/YNCwzcQH
Each first milestone value is set to 0. This should help circle positioning and interpolation when first milestone value is not 0. However no milestone should be set before the first actual value or there may be consequences.
> Added initial milestone value for every project 1 day before first actual value.

- portfolio_manager/templates/homepage.html
- portfolio_manager/views.py
https://trello.com/c/3WapJPEY
Add ready made presentations to non-admin user front page
> Presentations to non-admin user frontpage

- portfolio_manager/static/portfolio_manager/js/projectDependencies.js
https://trello.com/c/1dm5Xy0Y
dependancies nodes use their id's instead of their names to link each other. This enables duplicate names.
Also added missing semicolons and improved indentation.
> Dependancies node change

- portfolio_manager/forms.py
- portfolio_manager/models.py
https://trello.com/c/daOILw3y
all of the fields in add project form are set to required = False.
> Add project form requirement change

- portfolio_manager/views.py
"Select an organization" was an option in dropdown list with organizations. It has no value unlike the rest of the options, which caused a valueErrors when the value was used to get an organization object.
https://trello.com/c/WeIAvW1g
Also fixed the bugs which caused the table to look odd after adding a field.
https://trello.com/c/HYGgEy0C
> selecting "Select an organization" no longer causes an error at /database

- portfolio_manager/forms.py
- portfolio_manager/templates/database.html
- portfolio_manager/views.py
Orgadmin projectlisting now lists all projects from all the admin's orgGroups. This also fixes the "group has no employees/orgAdmins" error.
Projectlisting is fixed in following pages:
Homepage, projects, milestones
Also fixed database-view for orgAdmins, it now has the same org-dropdown superuser used to have but with only the organizations where the orgAdmin is an administrator
Finally orgAdmins do not have access to projects they shouldn't have (views.show.project)
https://trello.com/c/LriHoKka
> Organizationadmin projectlisting

- portfolio_manager/models.py
- portfolio_manager/static/portfolio_manager/js/datepickerLoader.js
- portfolio_manager/templates/modals/modify_modal.html
JQuery datepicker is used on IE and firefox, otherwise django´s default datepicker is used.
https://trello.com/c/GlnzKnbK
> Datepicker bug fix

- portfolio_manager/static/portfolio_manager/js/modify_project.js
- portfolio_manager/templates/add_project.html
- portfolio_manager/templates/modals/modify_modal.html
- portfolio_manager/templates/project.html
- portfolio_manager/views.py
Added Chosen everywhere except administrative tools and database. Added support for multiselects on assiciatedpersons and associatedprojects-dimensions. It is now possible to add one or more projects/persons to assiciatedperson- or assiciatedprojectdimensions
https://trello.com/c/3NMsHpCl
Fixed the dropdown-bug on project-page. The old solution used a common dropdown class to toggle all the dropdowns with the projects-dropdown.
https://trello.com/c/wEHYSCVY
Fixed the recursion error on project page when trying to add a value to a previously unused and unsaved dimension.
https://trello.com/c/uTdK21GW
> More chosen (and some fixes)

- portfolio_manager/static/portfolio_manager/js/modify_project.js
Chosen selects now show the default value correctly.
> Chosen selects now show the default value

- portfolio_manager/templates/about.html
Updating text to be more general and not only about portfolios
> Updating the purpose text

- portfolio_manager/static/portfolio_manager/css/fourField.css
- portfolio_manager/static/portfolio_manager/js/fourField.js
Moving fourfield ball information outside the field, adding numeric information about the ball and fixing bug that caused the balls to be located mirrored on y-axis. 
The colored ball next to info is there as in the future it should be possible to select few balls from the field to be examined more closely and therefore it is necessary to recognize said balls.
> FourField label update

- portfolio_manager/importer.py
- portfolio_manager/models.py
- portfolio_manager/views.py
Importer accepts decimals with both "," or "." and does not assume "owningOrganization" or "name" labeled fields to be found in the sheet.
This can be tested with huoneet1217 sheet located in Codento drive. Frontpage, projects page should not spit any errors and importer should accept all the rows in said sheet with "," as separator.
> Importer accepts decimals with both "," or "."
